GET http://localhost:8085/users

###
POST http://localhost:8085/login HTTP/1.1
content-type: application/json

{
    "username":"john","password":"password123"
}

###
POST http://localhost:3069/logout HTTP/1.1
content-type: application/json
